

meta:
  author: John Caserta
  homepage: http://thedesignoffice.org/project/modern-pictograms/
  email: info@johncaserta.com
  twitter: https://twitter.com/johncaserta
  licence: SIL
  licence_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4

transform:
  baseline: 0.5
  rescale: 1.0
  offset: 0.0

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: modernpics

  fullname: Modern Pictograms
  familyname: Modern Pictograms

  copyright: Copyright (c) 2012 by John Caserta. All rights reserved.

  ascent: 750
  descent: 250
  weight: Normal


glyphs:

  - css: glyph1
    code: 0x002b
    uuid: hbvhbnoivp3qj8xpyqrxa7dvq9ntnci3
    from: 0x002b
    search:

  - css: glyph2
    code: 0x0046
    uuid: w42gjpwdzqeszptpy1xqp8r77o6gcasj
    from: 0x0046
    search:

  - css: glyph3
    code: 0x0057
    uuid: b2i5x0ka1m6pskm3puj9jppl672knd5c
    from: 0x0057
    search:

  - css: glyph4
    code: 0x0045
    uuid: frauy9fser6zk9n5ih3rdpz7zzfjbrvu
    from: 0x0045
    search:

  - css: glyph5
    code: 0x0050
    uuid: 3f0r3y17tle74mzaafsx8frnp2nu36gg
    from: 0x0050
    search:

  - css: glyph6
    code: 0x0053
    uuid: px45pk7jgwms9zb3zcm44h8al4f3xxkd
    from: 0x0053
    search:

  - css: glyph7
    code: 0x0066
    uuid: ma9pq3m9ye6f33psotqr8e68yyv7fbz6
    from: 0x0066
    search:

  - css: glyph8
    code: 0x006b
    uuid: 99qmwsnyl7d1848xayggtcwaysc4e415
    from: 0x006b
    search:

  - css: glyph9
    code: 0x003e
    uuid: gypcofts1tkouwkxbv8d33eanqpreyy9
    from: 0x003e
    search:

  - css: glyph10
    code: 0x0070
    uuid: c1d1ix1r5ldq6yl3xwvh3u3fxqale7sy
    from: 0x0070
    search:

  - css: glyph11
    code: 0x003c
    uuid: am79573ydakwiicuct1odx7f2e9zv8lv
    from: 0x003c
    search:

  - css: glyph12
    code: 0x0024
    uuid: qdrxlsrgibi1n48dmygz3rp6ciczkjfs
    from: 0x0024
    search:

  - css: glyph13
    code: 0x0074
    uuid: h7disbowd4v177zjlsi6anz5nkka08uy
    from: 0x0074
    search:

  - css: glyph14
    code: 0x0065
    uuid: 6xuw5wrmz3ugf1ea2gyqj41n0qfkguqs
    from: 0x0065
    search:

  - css: glyph15
    code: 0x007c
    uuid: xvodj0yqtava9o2wbc0bc9czi2jft4db
    from: 0x007c
    search:

  - css: glyph16
    code: 0x0073
    uuid: id8wp0cygl9trzbhlbd9o0fygiesi629
    from: 0x0073
    search:

  - css: glyph17
    code: 0x0052
    uuid: v4mhug5rzlh2qzlo09kfx03e6e2alqql
    from: 0x0052
    search:

  - css: glyph18
    code: 0x0075
    uuid: qdhvqjd167ee2byleebhw58j4omhb8pl
    from: 0x0075
    search:

  - css: glyph19
    code: 0x0076
    uuid: dsfybb9l0x5fyd7e3o5kyisqppifztfu
    from: 0x0076
    search:

  - css: glyph20
    code: 0x005f
    uuid: o3ks7v0pzabyrzijuzxmzyzae06it2eh
    from: 0x005f
    search:

  - css: glyph21
    code: 0x0063
    uuid: 3v94fy782j1ddju9fbafpqa1x0li3bt6
    from: 0x0063
    search:

  - css: glyph22
    code: 0x0077
    uuid: i6ej1r6t84xouh0dct7g9zyx3ya9s9eg
    from: 0x0077
    search:

  - css: glyph23
    code: 0x0067
    uuid: d1a7ajpi3149rk5q4861jw9f2lzg27d1
    from: 0x0067
    search:

  - css: glyph24
    code: 0x004b
    uuid: t7uz7sms69yuckjmkp1zqggwr4jkw0o9
    from: 0x004b
    search:

  - css: glyph25
    code: 0x006d
    uuid: ae3so8q0b0n2h8esv9flua2nmwswa8fd
    from: 0x006d
    search:

  - css: glyph26
    code: 0x0058
    uuid: rrhco7mfj6ro9yzhe4a1rbln9flw47re
    from: 0x0058
    search:

  - css: glyph27
    code: 0x0078
    uuid: wcb87qh0k9smu6zukdhbn5zip98zofkh
    from: 0x0078
    search:

  - css: glyph28
    code: 0x0068
    uuid: ny7ydbn558y0aij4evvc199yt345tks4
    from: 0x0068
    search:

  - css: glyph29
    code: 0x0054
    uuid: uor1aru5x0tewrwsl36amx6hogjv61cs
    from: 0x0054
    search:

  - css: glyph30
    code: 0x0069
    uuid: vqyhv5kmwcj9zxq28dhq5npykr2k39co
    from: 0x0069
    search:

  - css: glyph31
    code: 0x006a
    uuid: pt5lb2orj9ms0n4yyxjavefdukcv1scl
    from: 0x006a
    search:

  - css: glyph32
    code: 0x006c
    uuid: jwebw8rhtovm6adljbdixtj9ltdrzkvb
    from: 0x006c
    search:

  - css: glyph33
    code: 0x270e
    uuid: 97var6sq7rzo72ktzg1c6ph46u9pftbr
    from: 0x270e
    search:

  - css: glyph34
    code: 0x0021
    uuid: f47srtt9pew19q6kg9jniwtzsb8q1rhy
    from: 0x0021
    search:

  - css: glyph35
    code: 0x005e
    uuid: 33iuue66u2628uv4kz3vnmh8uee8o7rw
    from: 0x005e
    search:

  - css: glyph36
    code: 0x29c9
    uuid: ft72kk8bqh8ioxgr8gi64kr2mzwqkqwi
    from: 0x29c9
    search:

  - css: glyph37
    code: 0x006e
    uuid: ivdkw88f6me1kxmgrk3qzv6jkgxhbuj7
    from: 0x006e
    search:

  - css: glyph38
    code: 0x0064
    uuid: 7ssl5z5jrhu13tb13cd3gb4bdfkzbfzw
    from: 0x0064
    search:

  - css: glyph39
    code: 0x004d
    uuid: hx5rpl1lxy10jqibjq0jmu0dhruapso4
    from: 0x004d
    search:

  - css: glyph40
    code: 0x004e
    uuid: raxalm7kdj5at9v49bevw6r2cw7fdv9r
    from: 0x004e
    search:

  - css: glyph41
    code: 0x0044
    uuid: kfk635sf697exf2r3jqx06zz54e1rgx4
    from: 0x0044
    search:

  - css: glyph42
    code: 0x0062
    uuid: 7idv5s1f3qkgmbwbat6xukumwqxkrook
    from: 0x0062
    search:

  - css: glyph43
    code: 0x0047
    uuid: 03cmb4p7niofd11yos3fpjjuvvpy7mji
    from: 0x0047
    search:

  - css: glyph44
    code: 0x006f
    uuid: fojo3y3ju5f4vge0bepcxl1mgmzgit9k
    from: 0x006f
    search:

  - css: glyph45
    code: 0x003f
    uuid: uda7inu4er17zsorrfic7n0l6fvukfqn
    from: 0x003f
    search:

  - css: glyph46
    code: 0x0071
    uuid: 8u06eo32zy61toyj78of6mi7inn3xlcl
    from: 0x0071
    search:

  - css: glyph47
    code: 0x007b
    uuid: 0ohst63cgq1mf1syayvfl8mphms8dbes
    from: 0x007b
    search:

  - css: glyph48
    code: 0x005b
    uuid: 3iwbntpxmp0kvbvzaxrh8h30xw1l6zvn
    from: 0x005b
    search:

  - css: glyph49
    code: 0x005c
    uuid: 3v2lgx3os8ub377alyqm8mn2o7r4zywg
    from: 0x005c
    search:

  - css: glyph50
    code: 0x005d
    uuid: giaskl13npzvuuz2ovy3vw8s0bewik08
    from: 0x005d
    search:

  - css: glyph51
    code: 0x0049
    uuid: z18zsyvbrpsea0f49kd61kkue1ofsafy
    from: 0x0049
    search:

  - css: glyph52
    code: 0x0041
    uuid: 1n2jlgp5brxxzpvvrly6jbfutnk2fpra
    from: 0x0041
    search:

  - css: glyph53
    code: 0x0072
    uuid: 587bjlxppui6u4japooa2foe58rsvicp
    from: 0x0072
    search:

  - css: glyph54
    code: 0x0042
    uuid: dplw5xo88mzzr7b45nvjcamyyhni6drs
    from: 0x0042
    search:

  - css: glyph55
    code: 0x005a
    uuid: 573lc53801tfc96xt7fubn59tb0o5s4y
    from: 0x005a
    search:

  - css: glyph56
    code: 0x0043
    uuid: 80fm9zvbe9habbzvsy6w4aymkgz2vu9i
    from: 0x0043
    search:

  - css: glyph57
    code: 0x0055
    uuid: gq8m9lqx2hhwxf7rz30adbr37rthzirq
    from: 0x0055
    search:

  - css: glyph58
    code: 0x0061
    uuid: pzy4lq1ak4datbxpdfj3ya74vjfhwxg1
    from: 0x0061
    search:

  - css: glyph59
    code: 0x0048
    uuid: vsvgkgr7wqknxe7rsjrusvvs43yekcyr
    from: 0x0048
    search:

  - css: glyph60
    code: 0x004a
    uuid: 9vefjlcta42r6tjjmog0mpx7mf63jgag
    from: 0x004a
    search:

  - css: glyph61
    code: 0x0079
    uuid: yc4vm9xepijcjyfdp6mgkvju8engb212
    from: 0x0079
    search:

  - css: glyph62
    code: 0x007a
    uuid: itjusjx5w85jr0udgi40mz7x2kmj1360
    from: 0x007a
    search:

  - css: glyph63
    code: 0x2018
    uuid: okkbiyf5ov5oo5iasofr8u2oq0hi425p
    from: 0x2018
    search:

  - css: glyph64
    code: 0x004c
    uuid: h9yii6q602rt4dxjmy9k9wc3jkwzk8d0
    from: 0x004c
    search:

  - css: glyph65
    code: 0x004f
    uuid: m3m8301t2xdy30x4lp7txm0vztl67tcl
    from: 0x004f
    search:

  - css: glyph66
    code: 0x003d
    uuid: 769oa3oy9cfucktpbod5cqmth9ioofxd
    from: 0x003d
    search:

  - css: glyph67
    code: 0x002c
    uuid: too2rspp5e6z6m0y6lconmv23uw3qlqo
    from: 0x002c
    search:

  - css: glyph68
    code: 0x0056
    uuid: 242giivkgr3e6le7b2xqi2pkdruf85mu
    from: 0x0056
    search:

  - css: glyph69
    code: 0x02c6
    uuid: 7r8dmidbi0sr907avu3hqwkdsxtxu1gy
    from: 0x02c6
    search:

  - css: glyph70
    code: 0x0032
    uuid: rrb2e7qiu68cw7itzq0wzm2hugw1u4lu
    from: 0x0032
    search:

  - css: glyph71
    code: 0x0031
    uuid: ivjrs8ijaooc3a2dw4790kb2rx4l6kjh
    from: 0x0031
    search:

  - css: glyph72
    code: 0x0030
    uuid: 8pcqxtjxtvkqo3dgemy49z7fw1d8xsh9
    from: 0x0030
    search:

  - css: glyph73
    code: 0x0051
    uuid: r36ey62e6pi493s139u528739kjr3o8w
    from: 0x0051
    search:

  - css: glyph74
    code: 0x0033
    uuid: o1c30odwfvgcvi5b4jsg95sur8v6ghsp
    from: 0x0033
    search:

  - css: glyph75
    code: 0x0034
    uuid: cy7vw87w1slwyalc4vd8cdhrb50asud3
    from: 0x0034
    search:

  - css: glyph76
    code: 0x0060
    uuid: e6t4yvmv401e9gpo2anslq4uqy2iz692
    from: 0x0060
    search:

  - css: glyph77
    code: 0x007d
    uuid: 9avusbdkm7q4vcmevr0x88zxewys65wr
    from: 0x007d
    search:

  - css: glyph78
    code: 0x002d
    uuid: 6ipws8y9gej6vbloufvhi5qux7rluf64
    from: 0x002d
    search:

  - css: glyph79
    code: 0x0059
    uuid: uetwmlvm6z9eaot1t74vvsgrte9vwi0n
    from: 0x0059
    search:

  - css: glyph80
    code: 0x0023
    uuid: fhpup8jff2yw9kmuwavhyqxogczcbbhj
    from: 0x0023
    search:

  - css: glyph81
    code: 0x0035
    uuid: sz7wtylc6qrwcbsj8aowal9y22hu6lka
    from: 0x0035
    search:

  - css: glyph82
    code: 0x0036
    uuid: 97ylvmgyj79w96iwzdanwmf5o4cvo17w
    from: 0x0036
    search:

  - css: glyph83
    code: 0x0020
    uuid: bypvjhplbo3soia7y6setdvnvbv7p5ve
    from: 0x0020
    search:

  - css: glyph84
    code: 0x0040
    uuid: mjbsqg8yglgu0esc6ru2vh111jmh7qng
    from: 0x0040
    search:

  - css: glyph85
    code: 0x00ec
    uuid: q5imh5yettm3jh1alrct9rso63hz6b3x
    from: 0x00ec
    search:

  - css: glyph86
    code: 0x0022
    uuid: rbniqxqcxbp09mkybz47x49nfaqh13j7
    from: 0x0022
    search:

  - css: glyph87
    code: 0x0025
    uuid: in76hg99crrkpcbz2rjnmgbiw74s72y0
    from: 0x0025
    search:

  - css: glyph88
    code: 0x002e
    uuid: s51at1xi1fkaomxvp6dqaax5jmyhtn4h
    from: 0x002e
    search:

  - css: glyph89
    code: 0x002f
    uuid: 8ax1xqcbzz1hobyd4i7f0unwib1bztip
    from: 0x002f
    search:

  - css: glyph90
    code: 0x002a
    uuid: kfzodo12ciruwganzy6h1bee2bpyz24d
    from: 0x002a
    search:

  - css: glyph91
    code: 0x0037
    uuid: ogmm8kz4f7y6ji50gzajnwed8h6ck2u7
    from: 0x0037
    search:

  - css: glyph92
    code: 0x0026
    uuid: v52bolk8ad7ctmir3srhnol1cx2i1yej
    from: 0x0026
    search:

  - css: glyph93
    code: 0x0038
    uuid: crns7fze53tnmwvi0wyfhq8whxfmmroz
    from: 0x0038
    search:

  - css: glyph94
    code: 0x0039
    uuid: uaps3vfayj05q7h4rvb10m890xvaequb
    from: 0x0039
    search:

  - css: glyph95
    code: 0x003a
    uuid: 2qh229aneb95ds2afi7dbdsxz9jrbhcl
    from: 0x003a
    search:

  - css: glyph96
    code: 0x003b
    uuid: snfl88dncpfb384hoi4rv4vqm08h8at8
    from: 0x003b
    search:

  - css: glyph97
    code: 0x00c4
    uuid: 3omin8gzar4t7r81y74kw7kcssfogngf
    from: 0x00c4
    search:

  - css: glyph98
    code: 0x0027
    uuid: ip65j4to6y8pionwfd8h22mbl6kp1xya
    from: 0x0027
    search:

  - css: glyph99
    code: 0x0028
    uuid: zc0c8s0nyweeeo9i8a3rucu7alwxt56r
    from: 0x0028
    search:

  - css: glyph100
    code: 0x0029
    uuid: lnyme20kl7kh26it9yrqk7at10k6i0sf
    from: 0x0029
    search:

  - css: glyph101
    code: 0x00d7
    uuid: 2w730675vjneyh80pks5b6f6f679vc6r
    from: 0x00d7
    search:
